apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: app1
        image: alpine:3.14
        tty: true
        stdin: true
        env:
          - name: foo
            value: bar
        resources:
          limits:
            memory: "72Mi"
            cpu: "100m"
      - name: app12
        image: httpd
